create database if not exists garuda;
use garuda;

create table if not exists GA_USER (
USR_ID varchar(20) primary key,
USR_NAME VARCHAR(20) NOT NULL,
USR_PASSWORD  VARCHAR(100) NOT NULL,
USR_MOBILE INT UNIQUE NOT NULL,
USR_EMAIL VARCHAR(20) UNIQUE NOT NULL,
USR_DESIGNATION VARCHAR(20) NOT NULL,
USR_PTR_ID INT  NULL,
USR_ACC_ID  INT NULL, 
USR_ROLE_ID CHAR(2) NOT NULL,
USR_IS_ACTIVE  boolean NOT NULL DEFAULT True,
USR_START_DATE  VARCHAR(20) NOT NULL,
USR_START_TIME  VARCHAR(20) NOT NULL,
USR_STOP_DATE  VARCHAR(20),
USR_STOP_TIME  VARCHAR(20) 
);

create table if not exists GA_PARTNER (
PTR_ID INT(10) AUTO_INCREMENT,
PTR_NAME VARCHAR(30) UNIQUE NOT NULL,
PTR_ADDRESS VARCHAR(50) NOT NULL,
PTR_IS_ACTIVE BOOLEAN NOT NULL DEFAULT True,
PTR_PAN_NO CHAR(20) UNIQUE NOT NULL,
PTR_GST  CHAR(20) UNIQUE NOT NULL,
PTR_CIN CHAR(20) UNIQUE NOT NULL,
PTR_CONTACT_NAME VARCHAR(20) NOT NULL,
PTR_CONTACT_NO UNIQUE INT NOT NULL,
PTR_CONTACT_EMAIL UNIQUE VARCHAR(50) NOT NULL, 
PTR_START_DATE VARCHAR(20) NOT NULL,
PTR_START_TIME VARCHAR(20) NOT NULL,
PTR_STOP_DATE VARCHAR(20),
PTR_STOP_TIME  VARCHAR(20),
PRIMARY KEY (PTR_ID)
);


create table if not exists GA_ACCOUNT (
ACC_ID INT AUTO_INCREMENT,
ACC_NAME VARCHAR(20) UNIQUE NOT NULL,
ACC_ADDRESS VARCHAR(50) NOT NULL,
ACC_IS_ACTIVE BOOLEAN NOT NULL DEFAULT True,
ACC_PAN CHAR(20) NOT NULL,
ACC_GST CHAR(20) NOT NULL,
ACC_CIN CHAR(20) NOT NULL,
ACC_CONTACT_NAME VARCHAR(20) NOT NULL,
ACC_CONTACT_NO INT NOT NULL,
ACC_CONTACT_EMAIL VARCHAR(50) NOT NULL,
ACC_START_DATE VARCHAR(20) NOT NULL,
ACC_START_TIME VARCHAR(20) NOT NULL,
ACC_STOP_DATE VARCHAR(20),
ACC_STOP_TIME VARCHAR(20),
PRIMARY KEY (ACC_ID)
);


create table if not exists GA_CAMERA(
CAM_ID INT NOT NULL AUTO_INCREMENT ,
			CAM_ACC_ID INT NOT NULL,
			CAM_DVR_IP VARCHAR(20) NOT NULL,
			CAM_CHENNAL INT NOT NULL,
			CAM_POC INT NOT NULL,
			CAM_LOCATION VARCHAR(30) NOT NULL,
			CAM_ALARM_CODE VARCHAR(20) NOT NULL,
			CAM_FPS INT DEFAULT 20 NOT NULL,
			PRIMARY KEY (CAM_ID)
);		

create table if not exists GA_CAM_USR_MAP (

CUM_USR_ID INT NOT NULL,
CUM_CAM_ID VARCHAR(20) NOT NULL

);
